import { Option } from "../interfaces/symbol-option.interface";

export const symbolOptions: Option[] = [
   { label: "3M Company", value: "MMM" },
   { label: "Abbott Laboratories", value: "ABT" },
   { label: "AbbVie Inc.", value: "ABBV" },
   { label: "Adobe Inc.", value: "ADBE" },
   { label: "Alphabet Inc. (Google)", value: "GOOGL" },
   { label: "Amazon.com, Inc.", value: "AMZN" },
   { label: "Amgen Inc.", value: "AMGN" },
   { label: "Apple Inc.", value: "AAPL" },
   { label: "AT&T Inc.", value: "T" },
   { label: "Bank of America Corporation", value: "BAC" },
   { label: "Berkshire Hathaway Inc.", value: "BRK.B" },
   { label: "Bristol-Myers Squibb Company", value: "BMY" },
   { label: "Broadcom Inc.", value: "AVGO" },
   { label: "Chevron Corporation", value: "CVX" },
   { label: "Cisco Systems, Inc.", value: "CSCO" },
   { label: "Coca-Cola Company", value: "KO" },
   { label: "CVS Health Corporation", value: "CVS" },
   { label: "Exxon Mobil Corporation", value: "XOM" },
   { label: "General Electric Company", value: "GE" },
   { label: "Honeywell International Inc.", value: "HON" },
   { label: "IBM Corporation", value: "IBM" },
   { label: "Intel Corporation", value: "INTC" },
   { label: "Johnson & Johnson", value: "JNJ" },
   { label: "Lilly (Eli) and Company", value: "LLY" },
   { label: "Lockheed Martin Corporation", value: "LMT" },
   { label: "Mastercard Incorporated", value: "MA" },
   { label: "Mastercard Incorporated", value: "MA" },
   { label: "Merck & Co., Inc.", value: "MRK" },
   { label: "Meta Platforms, Inc. (Facebook)", value: "META" },
   { label: "Microsoft Corporation", value: "MSFT" },
   { label: "Morgan Stanley", value: "MS" },
   { label: "Nike, Inc.", value: "NKE" },
   { label: "NVIDIA Corporation", value: "NVDA" },
   { label: "Oracle Corporation", value: "ORCL" },
   { label: "PayPal Holdings, Inc.", value: "PYPL" },
   { label: "PepsiCo, Inc.", value: "PEP" },
   { label: "Pfizer Inc.", value: "PFE" },
   { label: "Procter & Gamble Co.", value: "PG" },
   { label: "Qualcomm Incorporated", value: "QCOM" },
   { label: "Salesforce, Inc.", value: "CRM" },
   { label: "Tesla, Inc.", value: "TSLA" },
   { label: "Texas Instruments Incorporated", value: "TXN" },
   { label: "The Home Depot, Inc.", value: "HD" },
   { label: "The Walt Disney Company", value: "DIS" },
   { label: "Union Pacific Corporation", value: "UNP" },
   { label: "UnitedHealth Group Incorporated", value: "UNH" },
   { label: "Visa Inc.", value: "V" },
   { label: "Walmart Inc.", value: "WMT" },
   { label: "Wells Fargo & Company", value: "WFC" },
];
